### ISSUE TITLE
Can't resolve '@/' in ./node_modules/ferrugemjs/dist/core/bootstrapper.js

### ISSUE THREAD

**Issue by hassanzohdy** [ferrugemjs/skeleton-typescript#4]
Hello,

I just cloned this repo then executed`npm install` after that `npm run start`

Then i get the `@` error in the following files

`./node_modules/ferrugemjs/dist/core/bootstrapper.js` line `17`

```javascript
require(["@/" + app_url + templateExtension], function (_mod_init_app) {
```

Same error in `./node_modules/ferrugemjs/dist/core/component-factory.js` line `240`

```javascript

if (typeof __webpack_require__ === 'function') {
    require(["@/" + path + this.config.templateExtension], handlerLoad.bind(this));
}
```

I removed the `"@/"` from both files and the webpack compiler worked fine, but the `hello-world` component didn't compile in the browser

**P.S** Update the Getting started documentation replace `npm run watch` to `npm run start`

**Comment by ferrugemjs** [comment]
Hi @hassanzohdy, thanks for your feedback. Issue fixed in master now.
