### ISSUE TITLE
Html not loaded when calling component inside component

### ISSUE THREAD

**Issue by hassanzohdy** [ferrugemjs/skeleton-typescript#5]
Hello,

When i add `<card>` tag inside `hello-world` component the page is not loaded.

However, it loads fine if i removed the `card` tag from the page but when adding the card component it gives a blank page.

`app/hello-world/hello-world.html`

```html
<template>
	<require from="./../card/card" />
	<card></card>
	<div class="hello-world">
		<h4>${this.name}</h4>
		<ul>
			<li each="item in this.items">${item.name}</li>
		</ul>
	</div>
</template>

```
`app/card/card.html`

```html
<template>
	<h1 class="peep">Hello ${this.name}</h1>
</template>
```

**PS** The dom is rendering `<card>` tag as normal html tag but nothing below it.

**Comment by ferrugemjs** [comment]
Hi, I recommend use of "-" to avoid possible conflicts with possible dom tags.
eg.

<require from="./../card/card as box-card" />
<div>
 <box-card></box-card>
</div>








Em qua, 26 de dez de 2018 às 11:28, Hasan Zohdy <notifications@github.com>
escreveu:

**Comment by ferrugemjs** [comment]
to a more interactive help use https://gitter.im/ferrugemjs/questions

Em qua, 26 de dez de 2018 às 11:35, ferrugem javascript <
ferrugemjavascript@gmail.com> escreveu:
